---
- name: Install Gitolite3
  apt:
      name: gitolite3
      state: latest
  when: ( ansible_hostname == gitolite_server )
- name: Add user
  user:
      name: "{{ r10k_user }}"
      password: '*'
      home: "{{ r10k_homedir }}/{{ r10k_user }}"
      createhome: yes
      shell: /bin/sh
      comment: "{{ r10k_user }}"
      system: yes
  when: ( ansible_hostname == gitolite_server )
- name: Probe if set up
  stat:
      path: "{{ r10k_homedir }}/{{ r10k_user }}.gitolite"
  register: installation
  when: ( ansible_hostname == gitolite_server )
- name: Set up
  include_tasks: admin.yml
  when: ( installation.stat.exists == false and ansible_hostname == gitolite_server )
- name: copy gitolite.rc
  copy:
      src: files/gitolite.rc
      dest: "{{ r10k_homedir }}/{{ r10k_user }}.gitolite.rc"
      owner: "{{ r10k_user }}"
      group: "{{ r10k_user }}"
      mode: 0600
  when: ( ansible_hostname == gitolite_server )
- name: Create ssh folder
  file:
    state: directory
    path: "{{ r10k_homedir }}/{{ r10k_user }}/.ssh"
    mode: 0700
  when: ( ansible_hostname == gitolite_server )
- name: Copy secret key
  copy:
    src: "{{ ssh_key_src_path }}/{{ ssh_secret_key }}"
    dest: "{{ ssh_key_dest }}/{{ ssh_secret_key }}"
    mode: 0600
    owner: "{{ r10k_user }}"
  when: ( ansible_hostname == gitolite_server )
- name: Copy public key 
  copy:
    src: "{{ ssh_key_src_path }}/{{ ssh_secret_key }}.pub"
    dest: "{{ ssh_key_dest }}/{{ ssh_secret_key }}.pub"
    mode: 0600
    owner: "{{ r10k_user }}"
  when: ( ansible_hostname == gitolite_server )
- name: Copy script
  template:
    src: templates/setup_r10k.j2
    dest: /usr/local/bin/setup_r10k
    mode: 0755
  when: ( ansible_hostname == gitolite_server )
