---
- name: Install Ruby
  apt:
    name: ruby
    update_cache: yes

- name: Install Git
  apt:
    name: git
    update_cache: yes

- name: Install r10k
  command: gem install r10k
  args:
    creates: /usr/local/bin/r10k

- name: Create r10k folder
  file:
    path: /etc/puppetlabs/r10k
    state: directory
    owner: "{{ r10k_user }}"

- name: Copy r10k.yaml
  template: 
    src: r10k.j2
    dest: /etc/puppetlabs/r10k/r10k.yaml
    owner: "{{ r10k_user }}"

- name: Set up Puppet environments folder permissions
  file:
    state: directory
    path: "{{ r10k_homedir }}"
    owner: "{{ r10k_user }}"
    recurse: yes

- name: create .ssh folder
  file:
    path: "{{ r10k_homedir }}/.ssh"
    state: directory
    owner: "{{ r10k_user }}"
    group: "{{ r10k_user }}"
    mode: 0700

- name: Copy ssh config file
  template: 
    src: config.j2
    dest: "{{ r10k_homedir }}/.ssh/config"
    mode: 0600
    owner: "{{ r10k_user }}"

- name: Set up Puppet environments folder permissions
  file:
    state: directory
    path: "{{ puppet_env_dir }}"
    owner: "{{ r10k_user }}"
    recurse: yes

- name: Set up Puppet environments folder permissions
  file:
    state: directory
    path: '/etc/puppetlabs/puppetserver/'
    recurse: yes
    owner: "{{ r10k_user }}"

- name: Set up r10k cache folder
  file:
    state: directory
    path: /var/cache/r10k 
    owner: "{{ r10k_user }}"
    group: "{{ r10k_user }}"

- name: create puppet_deploy.sh script
  blockinfile:
    dest: "/tmp/puppet_deploy.sh"
    block: |
      sudo -n -H -u puppet bash -c "r10k deploy environment $1 --verbose --puppetfile"
    create: yes
    mode: 0770

- name: ensure github.com is a known host
  lineinfile:
    dest:  /opt/puppetlabs/server/data/puppetserver/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

#todo: Cronjob alle 10min